@host = http://localhost:8080/gestaocontato

### TOKEN

POST {{host}}/login
content-type: application/json

{
    "username": "user",
    "password": "123"
}

###################################### GET ######################################
### 200
GET {{host}}/user/contatos
Authorization: Basic admin 123

### 200
GET {{host}}/user/contatos?size=3&page=0
Authorization: Basic admin 123

### 401
GET {{host}}/user/contatos
Authorization: Basic admin 12

### 404
GET {{host}}/user/contato
Authorization: Basic admin 123


###################################### POST ######################################
### 201
POST {{host}}/admin/contatos
Content-Type: application/json
Authorization: Basic admin 123

{
    "nome": "251",
    "valor": "11111",
    "canal": "telefone"
}

### 400
POST {{host}}/admin/contatos
Content-Type: application/json
Authorization: Basic admin 123

{
    "valor": "11111",
    "canal": "telefone"
}

### 401
POST {{host}}/admin/contatos
Content-Type: application/json
Authorization: Basic admin 12

{
    "nome": "251",
    "valor": "11111",
    "canal": "telefone"
}

###################################### PUT ######################################
### 204
PUT {{host}}/admin/contatos/5
Content-Type: application/json
Authorization: Basic admin 123

{
    "nome": "teste",
    "valor": "11111",
    "canal": "telefone"
}

### 400
PUT {{host}}/admin/contatos/1
Content-Type: application/json
Authorization: Basic admin 123

{
    "valor": "11111",
    "canal": "telefone"
}

### 401
PUT {{host}}/admin/contatos/1
Content-Type: application/json
Authorization: Basic admin 12

{
    "nome": "teste",
    "valor": "11111",
    "canal": "telefone"
}

### 404
PUT {{host}}/admin/contato
Content-Type: application/json
Authorization: Basic admin 123

{
    "nome": "teste",
    "valor": "11111",
    "canal": "telefone"
}

###################################### DELETE ######################################
### 204
DELETE  {{host}}/admin/contatos/1
Authorization: Basic admin 123

### 401
DELETE  {{host}}/admin/contatos/2
Authorization: Basic admin 12

### 404
DELETE  {{host}}/admin/contatos/20
Authorization: Basic admin 123