@host = http://localhost:8080/gestaocontato

### TOKEN
# curl -d '{"username":"admin", "password":"123"}' -H "Content-Type: application/json" -X POST http://localhost:8080/gestaocontato/login

POST {{host}}/login
content-type: application/json

{
    "username": "admin",
    "password": "123"
}

###################################### GET ######################################
### 200
GET {{host}}/user/contatos
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTU2NDM1MzU3NH0.0VZfq3gaxxNeRuC6qqRJzIj72fdaAxDLqDkwFVWF9KT6wctQDVwttCC9FZgEQulE_kMBXpfNU096qKMKJZdytg%




### 200
GET {{host}}/user/contatos?size=3&page=0
Authorization: Basic admin 123

### 401
GET {{host}}/user/contatos
Authorization: Basic admin 12

### 404
GET {{host}}/user/contato
Authorization: Basic admin 123


###################################### POST ######################################
### 201
POST {{host}}/admin/contatos
Content-Type: application/json
Authorization: Basic admin 123

{
    "nome": "251",
    "valor": "11111",
    "canal": "telefone"
}

### 400
POST {{host}}/admin/contatos
Content-Type: application/json
Authorization: Basic admin 123

{
    "valor": "11111",
    "canal": "telefone"
}

### 401
POST {{host}}/admin/contatos
Content-Type: application/json
Authorization: Basic admin 12

{
    "nome": "251",
    "valor": "11111",
    "canal": "telefone"
}

###################################### PUT ######################################
### 204
PUT {{host}}/admin/contatos/5
Content-Type: application/json
Authorization: Basic admin 123

{
    "nome": "teste",
    "valor": "11111",
    "canal": "telefone"
}

### 400
PUT {{host}}/admin/contatos/1
Content-Type: application/json
Authorization: Basic admin 123

{
    "valor": "11111",
    "canal": "telefone"
}

### 401
PUT {{host}}/admin/contatos/1
Content-Type: application/json
Authorization: Basic admin 12

{
    "nome": "teste",
    "valor": "11111",
    "canal": "telefone"
}

### 404
PUT {{host}}/admin/contato
Content-Type: application/json
Authorization: Basic admin 123

{
    "nome": "teste",
    "valor": "11111",
    "canal": "telefone"
}

###################################### DELETE ######################################
### 204
DELETE  {{host}}/admin/contatos/1
Authorization: Basic admin 123

### 401
DELETE  {{host}}/admin/contatos/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNTY0MzUwNzcxfQ.DuwbAnYmbqGEWTozGXvcbbVgA4DP_wMleUKs0dYZjcoeELS6o3tB2td-brwEd8HL5-s9ZJ31LCCqslO23dzfKw


### 404
DELETE  {{host}}/admin/contatos/20
Authorization: Basic admin 123