server:
  servlet:
    context-path: /gestaocontato

spring:
    jpa:
        hibernate:
            ddl-auto: create
            use-new-id-generator-mappings: true
        open-in-view: true
    datasource:
        url: jdbc:h2:mem:gesconDB;DB_CLOSE_ON_EXIT=FALSE
    h2:
        console:
            enabled: true
    data:
        web:
            pageable:
                default-page-size: 10
                max-page-size: 20
                one-indexed-parameters: true
