INSERT INTO USUARIO (ID, USERNAME, SENHA, NOME) VALUES (1, 'joao',  '$2a$10$L5cFV4qQ.7ar0du4u5SNkul.I6x5IvJugeOYmBEfpiBdmPlE59fSy', 'JOÃO')
INSERT INTO USUARIO (ID, USERNAME, SENHA, NOME) VALUES (2, 'maria', '$2a$10$L5cFV4qQ.7ar0du4u5SNkul.I6x5IvJugeOYmBEfpiBdmPlE59fSy', 'MARIA')

INSERT INTO GRUPO VALUES (1, 'ADMINISTRADOR')
INSERT INTO GRUPO VALUES (2, 'USUARIO')

INSERT INTO USUARIO_GRUPO VALUES (1,2)
INSERT INTO USUARIO_GRUPO VALUES (2,1)
INSERT INTO USUARIO_GRUPO VALUES (2,2)


