INSERT INTO USUARIO (ID, USERNAME, PASSWORD, NAME) VALUES (1, 'admin', '$2a$10$Q57vX/h23wJB6prg012VHe/iLvhEsrXP0X9teuUjLZakZb46K7VIK', 'MARIA')
INSERT INTO USUARIO (ID, USERNAME, PASSWORD, NAME) VALUES (2, 'user', '$2a$10$Q57vX/h23wJB6prg012VHe/iLvhEsrXP0X9teuUjLZakZb46K7VIK', 'JOAO')
--YWRtaW46MTIz
--dXNlcjoxMjM=

INSERT INTO GRUPO VALUES (1, 'ADMINISTRADOR')
INSERT INTO GRUPO VALUES (2, 'USUARIO')

INSERT INTO USUARIO_GRUPO VALUES (1,1)
INSERT INTO USUARIO_GRUPO VALUES (1,2)
INSERT INTO USUARIO_GRUPO VALUES (2,2)



