INSERT INTO USUARIO (ID, USERNAME, PASSWORD, NAME) VALUES (1, 'admin', '$2a$10$Q57vX/h23wJB6prg012VHe/iLvhEsrXP0X9teuUjLZakZb46K7VIK', 'MARIA')
INSERT INTO USUARIO (ID, USERNAME, PASSWORD, NAME) VALUES (2, 'user', '$2a$10$Q57vX/h23wJB6prg012VHe/iLvhEsrXP0X9teuUjLZakZb46K7VIK', 'JOAO')
--YWRtaW46MTIz
--dXNlcjoxMjM=

INSERT INTO GRUPO VALUES (1, 'ADMINISTRADOR')
INSERT INTO GRUPO VALUES (2, 'USUARIO')

INSERT INTO USUARIO_GRUPO VALUES (1,1)
INSERT INTO USUARIO_GRUPO VALUES (1,2)
INSERT INTO USUARIO_GRUPO VALUES (2,2)


INSERT INTO CONTATO (ID, NOME, CANAL, VALOR, OBS) VALUES (1, 'CONTATO 01', 'EMAIL', 'CONTATO_01@EMAIL.COM', 'OBSERVAÇÃO 01')
INSERT INTO CONTATO (ID, NOME, CANAL, VALOR, OBS) VALUES (2, 'CONTATO 02', 'EMAIL', 'CONTATO_02@EMAIL.COM', 'OBSERVAÇÃO 02')
INSERT INTO CONTATO (ID, NOME, CANAL, VALOR, OBS) VALUES (3, 'CONTATO 03', 'EMAIL', 'CONTATO_03@EMAIL.COM', 'OBSERVAÇÃO 03')
INSERT INTO CONTATO (ID, NOME, CANAL, VALOR, OBS) VALUES (4, 'CONTATO 04', 'EMAIL', 'CONTATO_04@EMAIL.COM', 'OBSERVAÇÃO 04')
INSERT INTO CONTATO (ID, NOME, CANAL, VALOR, OBS) VALUES (5, 'CONTATO 05', 'EMAIL', 'CONTATO_05@EMAIL.COM', 'OBSERVAÇÃO 05')
INSERT INTO CONTATO (ID, NOME, CANAL, VALOR, OBS) VALUES (6, 'CONTATO 06', 'EMAIL', 'CONTATO_06@EMAIL.COM', 'OBSERVAÇÃO 06')
INSERT INTO CONTATO (ID, NOME, CANAL, VALOR, OBS) VALUES (7, 'CONTATO 07', 'EMAIL', 'CONTATO_07@EMAIL.COM', 'OBSERVAÇÃO 07')
INSERT INTO CONTATO (ID, NOME, CANAL, VALOR, OBS) VALUES (8, 'CONTATO 08', 'EMAIL', 'CONTATO_08@EMAIL.COM', 'OBSERVAÇÃO 08')
INSERT INTO CONTATO (ID, NOME, CANAL, VALOR, OBS) VALUES (9, 'CONTATO 09', 'EMAIL', 'CONTATO_09@EMAIL.COM', 'OBSERVAÇÃO 09')
INSERT INTO CONTATO (ID, NOME, CANAL, VALOR, OBS) VALUES (10, 'CONTATO 10', 'EMAIL', 'CONTATO_10@EMAIL.COM', 'OBSERVAÇÃO 10')
INSERT INTO CONTATO (ID, NOME, CANAL, VALOR, OBS) VALUES (11, 'CONTATO 11', 'EMAIL', 'CONTATO_11@EMAIL.COM', 'OBSERVAÇÃO 11')
INSERT INTO CONTATO (ID, NOME, CANAL, VALOR, OBS) VALUES (12, 'CONTATO 12', 'EMAIL', 'CONTATO_12@EMAIL.COM', 'OBSERVAÇÃO 12')
INSERT INTO CONTATO (ID, NOME, CANAL, VALOR, OBS) VALUES (13, 'CONTATO 13', 'EMAIL', 'CONTATO_13@EMAIL.COM', 'OBSERVAÇÃO 13')
INSERT INTO CONTATO (ID, NOME, CANAL, VALOR, OBS) VALUES (14, 'CONTATO 14', 'EMAIL', 'CONTATO_14@EMAIL.COM', 'OBSERVAÇÃO 14')
INSERT INTO CONTATO (ID, NOME, CANAL, VALOR, OBS) VALUES (15, 'CONTATO 15', 'EMAIL', 'CONTATO_15@EMAIL.COM', 'OBSERVAÇÃO 15')

